server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: quran-memorization-app
  
  datasource:
    url: jdbc:mysql://localhost:3306/quran_memorization?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  security:
    user:
      name: admin
      password: admin123

logging:
  level:
    com.quran: DEBUG
    org.springframework.security: DEBUG

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours in milliseconds
